// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function Get(arg1:string):Promise<services.Recipe>;

export function List():Promise<Array<services.RecipeSummary>>;

export function OpenRecipeDir():Promise<void>;

export function Reload():Promise<services.ReloadResult>;

export function Validate(arg1:string):Promise<services.ValidationResult>;
