// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get(arg1) {
  return window['go']['services']['RecipeService']['Get'](arg1);
}

export function List() {
  return window['go']['services']['RecipeService']['List']();
}

export function OpenRecipeDir() {
  return window['go']['services']['RecipeService']['OpenRecipeDir']();
}

export function Reload() {
  return window['go']['services']['RecipeService']['Reload']();
}

export function Validate(arg1) {
  return window['go']['services']['RecipeService']['Validate'](arg1);
}
