// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['services']['ScaffoldService']['Cancel'](arg1);
}

export function Logs(arg1, arg2) {
  return window['go']['services']['ScaffoldService']['Logs'](arg1, arg2);
}

export function OpenInEditor(arg1, arg2) {
  return window['go']['services']['ScaffoldService']['OpenInEditor'](arg1, arg2);
}

export function PickDirectory(arg1) {
  return window['go']['services']['ScaffoldService']['PickDirectory'](arg1);
}

export function Plan(arg1) {
  return window['go']['services']['ScaffoldService']['Plan'](arg1);
}

export function RevealInFileManager(arg1) {
  return window['go']['services']['ScaffoldService']['RevealInFileManager'](arg1);
}

export function Start(arg1) {
  return window['go']['services']['ScaffoldService']['Start'](arg1);
}

export function Status(arg1) {
  return window['go']['services']['ScaffoldService']['Status'](arg1);
}
