// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function Cancel(arg1:string):Promise<void>;

export function Logs(arg1:string,arg2:number):Promise<Array<services.LogLine>>;

export function OpenInEditor(arg1:string,arg2:string):Promise<void>;

export function PickDirectory(arg1:string):Promise<string>;

export function Plan(arg1:services.ScaffoldRequest):Promise<services.Plan>;

export function RevealInFileManager(arg1:string):Promise<void>;

export function Start(arg1:services.ScaffoldRequest):Promise<services.Job>;

export function Status(arg1:string):Promise<services.Job>;
