// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['services']['StoreService']['ClearHistory']();
}

export function DeleteHistoryEntry(arg1) {
  return window['go']['services']['StoreService']['DeleteHistoryEntry'](arg1);
}

export function DeletePreset(arg1) {
  return window['go']['services']['StoreService']['DeletePreset'](arg1);
}

export function GetSettings() {
  return window['go']['services']['StoreService']['GetSettings']();
}

export function ListHistory(arg1) {
  return window['go']['services']['StoreService']['ListHistory'](arg1);
}

export function ListPresets() {
  return window['go']['services']['StoreService']['ListPresets']();
}

export function SavePreset(arg1) {
  return window['go']['services']['StoreService']['SavePreset'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['services']['StoreService']['SaveSettings'](arg1);
}
