// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function ClearHistory():Promise<void>;

export function DeletePreset(arg1:string):Promise<void>;

export function GetSettings():Promise<services.Settings>;

export function ListHistory(arg1:number):Promise<Array<services.HistoryEntry>>;

export function ListPresets():Promise<Array<services.Preset>>;

export function SavePreset(arg1:services.Preset):Promise<void>;

export function SaveSettings(arg1:services.Settings):Promise<void>;
