// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function Detect(arg1:boolean):Promise<services.Toolchain>;

export function ResolvedPath():Promise<string>;

export function SetPathOverride(arg1:string):Promise<void>;
