// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Detect(arg1) {
  return window['go']['services']['ToolchainService']['Detect'](arg1);
}

export function ResolvedPath() {
  return window['go']['services']['ToolchainService']['ResolvedPath']();
}

export function SetPathOverride(arg1) {
  return window['go']['services']['ToolchainService']['SetPathOverride'](arg1);
}
